paths:
  # =========================
  # CACHE (su questo disco/repo)
  # =========================
  cache_dir: ".cache/"
  hf_home: ".cache/huggingface/"
  datasets_cache_dir: ".cache/huggingface/datasets/"
  torch_home: ".cache/torch/"

  # =========================
  # DATA
  # =========================
  raw_data_dir: "data/raw/"
  local_data_dir: "data/local/"
  cleaned_data_dir: "data/cleaned/"
  shards_dir: "data/shards/"
  tokenizer_dir: "data/tokenizer/"

  # =========================
  # MODEL
  # =========================
  model_output_dir: "checkpoints/"
  final_model_dir: "model/"

  # =========================
  # LOGS
  # =========================
  logs_dir: "logs/"
